version: '3.8'

services:
  cassandra:
    image: scylladb/scylla:latest
    container_name: cassandra
    ports:
      - "9042:9042"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
